name: Deploy Latios-Sign

on:
  push:
    branches: [ main ] # Se ejecuta cada vez que subas algo a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 30m
          script: |
            if [ ! -d "latios-sign" ]; then
              git clone https://github.com/${{ github.repository }}.git latios-sign
            fi
            cd latios-sign
            git pull origin main
            
            # Generamos el archivo con TODOS los datos necesarios
            echo "POSTGRES_USER=latios" > infra/.env.prod
            echo "POSTGRES_DB=latios" >> infra/.env.prod
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> infra/.env.prod
            
            # Esta URL es la que usarÃ¡ NestJS (Prisma/TypeORM) para conectar
            echo "DATABASE_URL=postgresql://latios:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/latios?schema=public" >> infra/.env.prod
            
            docker compose -f infra/docker-compose.prod.yml --env-file infra/.env.prod up -d --build
            docker image prune -f